//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int idVehiculo { get; set; }
        public Nullable<int> idTipo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string matricula { get; set; }
        public Nullable<decimal> coste { get; set; }
    
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
